version: '3.8'

services:

  portainer:
    image: portainer/portainer-ce:latest  # Definir a imagem corretamente
    command: -H tcp://host.docker.internal:2375
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      restart_policy:
         condition: on-failure
  
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: dbProjeto
      POSTGRES_USER: Sofia
      POSTGRES_PASSWORD: senha1234
    volumes:
      - portainer_postgres_data:/var/lib/postgresql/data

  projeto:   
    build: .
    image: imagem_projeto:latest
    volumes:
      - projeto_postgres_data:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: dbProjeto
      DB_USER: Sofia
      DB_PASSWORD: senha1234
      DB_HOST: db
      DB_PORT: 5432

  
volumes:
  portainer_postgres_data: {}  
  projeto_postgres_data: {}



