# Generated by Django 5.1.4 on 2025-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], max_length=1),
        ),
    ]
