# Generated by Django 5.1.4 on 2025-01-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_tarefa_coluna_remove_tarefa_quadro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lista', to='API.quadro')),
            ],
        ),
    ]
