# Generated by Django 5.1.4 on 2025-01-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_quadro_lista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['id'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='quadro',
            options={'ordering': ['id'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
