# Generated by Django 5.1.4 on 2025-01-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_lista_options_alter_quadro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['id'], 'verbose_name': 'Lista', 'verbose_name_plural': 'Listas'},
        ),
        migrations.AlterModelOptions(
            name='quadro',
            options={'ordering': ['id'], 'verbose_name': 'Quadro', 'verbose_name_plural': 'Quadros'},
        ),
    ]
