# Generated by Django 5.1.4 on 2025-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_lista_options_alter_quadro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
